inherit_from: .rubocop_todo.yml

Layout/BlockAlignment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Naming/MethodName:
  Exclude:

Metrics/ParameterLists:
  Enabled: false

Metrics/ModuleLength:

Layout/CommentIndentation:

Layout/MultilineMethodCallIndentation:

Style/ClassAndModuleChildren:


Style/ExpandPathArguments:
  Exclude:
    - 'potato_debugger.gemspec'

Style/Semicolon:

Style/SingleLineMethods:

Style/StringLiterals:
  Enabled: false

Metrics/LineLength:
  Max: 90

Bundler/OrderedGems:
  Enabled: true

Style/DoubleNegation:
  Enabled: false

Style/Documentation:
  Enabled: true

Style/CommentedKeyword:

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
